project_id = "diphacbvdhfzdqfkobkl"

[functions]
public_routes = {}

[functions.flight-monitor]
verify_jwt = true
import_map = "./import_map.json"

[functions.parse-travel-document]
verify_jwt = true
import_map = "./import_map.json"

[functions.handle-travel-email]
verify_jwt = true
import_map = "./import_map.json"

[functions.ai-document-parser]
verify_jwt = true
import_map = "./import_map.json"

[functions.email-webhook]
verify_jwt = false
import_map = "./import_map.json"

[functions.wikivoyage-search]
verify_jwt = true
import_map = "./import_map.json"

