// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diphacbvdhfzdqfkobkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcGhhY2J2ZGhmemRxZmtvYmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjQ5MzIsImV4cCI6MjA2MTA0MDkzMn0.23OcawUv1A5Vrt_wD0gnHUnSRD4FxoioROLc-WgZPU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);